'use strict';

// tests for getShoppingCart
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getShoppingCart', '/handler.js', 'getShoppingCart');

describe('getShoppingCart', () => {
  before((done) => {
    done();
  });

  it('should return 200', async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
    expect(response.body).to.not.be.empty;
    expect(response.statusCode).to.be.eql(200);
  });
});
