'use strict';

// tests for removeProductToCart
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('removeProductToCart', '/handler.js', 'removeProductToCart');
let addProduct = mochaPlugin.getWrapper('addProductToCart', '/handler.js', 'addProductToCart');

describe('removeProductToCart', () => {
  before((done) => {
    done();
  });

  it('should return 200 if deleting an existing cart item.', async () => {
    const addProductResponse = await addProduct.run({
      body: JSON.stringify({
        "product_id": "6245b52a8f1cfd769ee344b6",
        "user_id": "1",
        "quantity": "test"
      })
    });

    const response = await wrapped.run({
      pathParameters: {
        id: addProductResponse.body.id
      }
    });
    expect(response).to.not.be.empty;
    expect(response.body).to.not.be.empty;
    expect(response.statusCode).to.be.eql(200);
  });

  it('should return 500 if deleting a non existing cart item.', async () => {

    const response = await wrapped.run({
      pathParameters: {
        id: "1234567"
      }
    });
    expect(response).to.not.be.empty;
    expect(response.body).to.not.be.empty;
    expect(response.statusCode).to.be.eql(500);
  });
});
